name: Build PR when labeled

on:
  pull_request:
    types: [ labeled ]

jobs:
  remove-label:
    uses: canonical/inference-snaps-dev/.github/workflows/remove-label.yaml@main

  build-and-publish:
    needs: remove-label
    uses: canonical/inference-snaps-dev/.github/workflows/build-publish-snap.yaml@main
    with:
      init-build-script: 'prepare-models.sh'
      # Build head of PR
      build-sha: ${{ github.event.pull_request.head.sha }}
      # Publish to a channel with the pr number in it
      publish-channel: latest/edge/pr-${{ github.event.pull_request.number }} # Add track if needed, e.g., 24/latest/edge/pr-#
    secrets:
      store-credentials: ${{ secrets.STORE_LOGIN }}
