name: Snap CI

on:
  # Use pull_request_target to grant write access to the PR
  # This event runs from the context of the base of the PR rather than its head, affecting the default checkout behavior
  pull_request_target:
    types: [ labeled ]
  
  push:
    branches: [ main ]

  # Allow manual trigger
  workflow_dispatch:


jobs:
  trigger:
    name: Comment and trigger build
    if: github.event_name == 'push' || 
      (github.event_name == 'pull_request_target' && github.event.label.name == 'needs-build') 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # needed to comment on PR
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Comment on the PR
        if: github.event_name == 'pull_request_target'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          
          COMMIT_SHA="${{ github.event.pull_request.head.sha }}"
          COMMIT_URL="${{ github.server_url }}/${{ github.repository }}/commit/$COMMIT_SHA"
          PR_NUMBER=${{ github.event.pull_request.number }}
          
          gh pr comment $PR_NUMBER --body "Snap build: [workflow run]($RUN_URL) | $COMMIT_URL"

  build:
    name: Build and publish snap
    needs: [trigger]
    strategy:
      fail-fast: false
      matrix:
        runs:
          - architecture: amd64
            runner: [ self-hosted, linux, amd64, xlarge, noble ]
          - architecture: arm64
            runner: [ self-hosted, linux, arm64, xlarge, noble ]
    runs-on: ${{ matrix.runs.runner }}

    steps:
      # Update snapd as we need a recent one to support components
      - name: Update snapd
        run: |
          sudo snap refresh snapd

      - name: Install Git LFS
        run: sudo apt-get update && sudo apt-get install -y git-lfs

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          lfs: true
          submodules: true
          # When triggered by pull_request_target, checkout PR's HEAD (rather than base), otherwise use github.sha
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Prepare models
        run: |
          # gemma-3-4b-it-ov-int4-fq
          pushd components/model-4b-it-int4-fq-ov
          git clone --depth 1 https://huggingface.co/llmware/gemma-3-4b-it-ov-int4-fq
          git -C gemma-3-4b-it-ov-int4-fq lfs prune --force
          ln -s /tmp/graph.pbtxt ./gemma-3-4b-it-ov-int4-fq/graph.pbtxt
          popd


      - name: Build snap
        uses: canonical/action-build@v1

      # Requires STORE_LOGIN secret set. Export with:
      # snapcraft export-login --snaps gemma3 --channels */edge/* --acls package_access,package_push,package_update,package_release --expires 2026-11-01T00:00:00Z <file>
      - name: Publish snap
        uses: canonical/inference-snaps-dev/actions/publish@main
        with:
          store-credentials: ${{ secrets.STORE_LOGIN }}

  clean:
    name: Remove label
    needs: [trigger, build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # needed to remove the label
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        
      - name: Remove 'needs-build' label
        if: github.event_name == 'pull_request_target'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          gh pr edit $PR_NUMBER --remove-label "needs-build"
