name: Validate engine manifests
on: [pull_request]

jobs:
  validate:
    runs-on: [ ubuntu-latest ]
    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Checkout inference-snap-cli 
        uses: actions/checkout@v6
        with:
          repository: canonical/inference-snaps-cli
          path: inference-snaps-cli

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.x'

      - name: Run validation
        run: |
          cd inference-snaps-cli/cmd/cli
          go run . debug validate-engines ../../../engines/**/*.yaml
