name: Verify engine manifests
on: [pull_request]

jobs:
  verify-manifests:
    runs-on: [ self-hosted, linux, amd64, medium, noble ]
    steps:

      - name: Install Git LFS
        run: sudo apt-get update && sudo apt-get install -y git-lfs

      - name: Checkout code
        uses: actions/checkout@v5
        with:
          lfs: true
          submodules: true
          token: ${{ secrets.SUBMODULE_PAT }}

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.x'

      - name: Run validation
        run: |
          cd cli/cmd/cli
          go run . debug validate-engines ../../../engines/**/*.yaml
